resources:
- repo: self
  clean: true
queue:
  name: Hosted
  demands: 
  - npm
  - DotNetFramework
name: 1.3$(Rev:.r)
steps:
- task: Npm@0
  displayName: 'npm install'
  inputs:
    arguments: '-g vsce'

- task: CmdLine@1
  displayName: 'Run vsce '
  inputs:
    filename: 'vsce '
    arguments: package
    workingFolder: '$(build.artifactstagingdirectory)\extension\'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: azdo-pipeline-snippets-$(Build.BuildNumber).vsix'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\extension\azdo-pipeline-snippets-$(Build.BuildNumber).vsix'
    ArtifactName: 'azdo-pipeline-snippets-$(Build.BuildNumber).vsix'



